name: Deploy
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.dsclub_space}}
          name: id_rsa
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: rsync over SSH
        run: rsync ./ root@92.53.104.199:bar/